include:
  - config/boards/shields/sofle_left.conf
  - config/boards/shields/sofle_right.conf
  - config/prj.conf

  - board: nice_nano_v2
    shield: sofle_left
    # snippet oficial p/ Studio via USB (preferido)
    snippet: studio-rpc-usb-uart
    # mantemos apenas flags do ZMK aqui
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_USB=y

  - board: nice_nano_v2
    shield: sofle_right
    # você pode manter o snippet atual do right ou nenhum; não afeta o teste do left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
