name: Build ZMK Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init West (pull ZMK via manifest)
        run: |
          python3 --version
          pip3 --version
      
          # Garante 'west' disponível e no PATH
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          west --version
      
          # Inicializa projeto com o manifest em config/west.yml
          west init -l config
          west update
          west zephyr-export
      
          # Dependências do Zephyr/ZMK
          pip3 install --user -r zephyr/scripts/requirements.txt


      - name: Build LEFT
        run: |
          west build -s zmk/app -d build/left -b nice_nano_v2 -- \
            -DSHIELD=sofle_left \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config \
            -DCONFIG_ZMK_STUDIO=y \
            -DSNIPPET=studio-rpc-usb-uart

      - name: Build RIGHT
        run: |
          west build -s zmk/app -d build/right -b nice_nano_v2 -- \
            -DSHIELD=sofle_right \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config \
            -DCONFIG_ZMK_STUDIO=y \
            -DSNIPPET=studio-rpc-usb-uart

      - name: Build SETTINGS_RESET
        run: |
          west build -s zmk/app -d build/reset -b nice_nano_v2 -- \
            -DSHIELD=settings_reset \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
            build/reset/zephyr/zmk.uf2
